version: '3.8'

services:
    db:
        image: mysql:8.0
        volumes:
            - ./mysql-data:/var/lib/mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD:
            MYSQL_DATABASE:
            MYSQL_USER:
            MYSQL_PASSWORD:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8081:8080"
        environment:
            SPRING_DATASOURCE_URL:
            SPRING_DATASOURCE_USERNAME:
            SPRING_DATASOURCE_PASSWORD:
            SPRING_JPA_HIBERNATE_DDL_AUTO:
            SPRING_MAIL_HOST:
            SPRING_MAIL_PORT:
            SPRING_MAIL_USERNAME:
            SPRING_MAIL_PASSWORD:
            JWT_SECRET:
            JWT_EXPIRATION: 3600000
            API_BASE_URL:
        depends_on:
            - db
